apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: c2c-monitor
resources:
  - namespace.yaml
  - database.yaml
  - application.yaml
  - ingress.yaml
configMapGenerator:
  - name: c2c-monitor-frontend-runtime
    namespace: c2c-monitor
    files:
      - nginx.conf=frontend-nginx.conf
      - config.js=frontend-config.js
generatorOptions:
  disableNameSuffixHash: true
